enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# --- BAGIAN TOOLS (Wajib Inotia00) ---
[tools]
patches_source = "inotia00/revanced-patches"
integrations_source = "inotia00/revanced-integrations"
cli_source = "inotia00/revanced-cli"

# --- BAGIAN APLIKASI ---
[[apps]]
name = "YouTube"
pkg_name = "com.google.android.youtube"
version = "auto" # PENTING: Cek target version di repo inotia00/revanced-patches!
build_mode = "module" # Output jadi zip Magisk

# --- PENGATURAN EXCLUDE (Hapus Branding) ---
excluded_patches = [
    "custom-branding-name",      # Nama balik jadi "YouTube"
    "custom-branding-icon",      # Icon balik jadi Merah Original
    "custom-splash-animation",   # Animasi loading asli
    "debugging",                 # Buang log sampah (wajib)
    "gms-core-support"           # BENAR di-exclude HANYA jika Anda ROOT/Magisk
]
